window.ANTIKOR_CARS = [
  {
    id: "jolion",
    brand: "HAVAL",
    model: "Jolion",
    year: 2025,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Передний",
    mileage: 0,
    color: "Белый",
    owners: 0,
    type: "new",
    price: 2149000,
    credit: 18990,
    img: "assets/cars/car1.png",
    gallery: ["assets/cars/car1.png", "assets/cars/car-left.webp", "assets/cars/car-right.webp"],
    logo: "assets/partners/haval.webp",
    badges: ["В наличии", "Официальный дилер"],
    equipment: [
      { title: "Безопасность", items: ["ABS", "ESP", "6 подушек безопасности", "Камера заднего вида"] },
      { title: "Мультимедиа", items: ["Экран 10.25\"", "Apple CarPlay / Android Auto", "Bluetooth"] },
      { title: "Комфорт", items: ["Климат-контроль", "Подогрев сидений", "Круиз-контроль"] },
    ],
  },
  {
    id: "dargo",
    brand: "HAVAL",
    model: "Dargo",
    year: 2025,
    body: "Кроссовер",
    engine: "2.0 л",
    hp: 192,
    fuel: "Бензин",
    transmission: "Автомат",
    drive: "Полный",
    mileage: 0,
    color: "Серый",
    owners: 0,
    type: "new",
    price: 2899000,
    credit: 24990,
    img: "assets/cars/car-right2.png",
    gallery: ["assets/cars/car-right2.png", "assets/cars/car-profile.webp", "assets/cars/car1.png"],
    logo: "assets/partners/haval.webp",
    badges: ["Полный привод", "Топ продаж"],
    equipment: [
      { title: "Безопасность", items: ["Адаптивный круиз", "Мониторинг слепых зон", "ESP"] },
      { title: "Мультимедиа", items: ["Панорамный экран", "Навигация", "Камеры 360°"] },
      { title: "Салон", items: ["Кожа", "Подогрев руля", "Вентиляция сидений"] },
    ],
  },
  {
    id: "m6",
    brand: "HAVAL",
    model: "M6",
    year: 2025,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Передний",
    mileage: 0,
    color: "Чёрный",
    owners: 0,
    type: "new",
    price: 1999000,
    credit: 17490,
    img: "assets/cars/car-left.webp",
    gallery: ["assets/cars/car-left.webp", "assets/cars/car1.png"],
    logo: "assets/partners/haval.webp",
    badges: ["Выгода до 150 000 ₽"],
    equipment: [
      { title: "Безопасность", items: ["ABS", "ESP", "Парктроник"] },
      { title: "Мультимедиа", items: ["Сенсорный экран", "USB", "Bluetooth"] },
    ],
  },
  {
    id: "coolray",
    brand: "GEELY",
    model: "Coolray",
    year: 2025,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 177,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Передний",
    mileage: 0,
    color: "Синий",
    owners: 0,
    type: "new",
    price: 2349000,
    credit: 20490,
    img: "assets/cars/car-right.webp",
    gallery: ["assets/cars/car-right.webp", "assets/cars/car-profile.webp"],
    logo: "assets/partners/geely.webp",
    badges: ["Спорт-дизайн"],
    equipment: [
      { title: "Динамика", items: ["Турбомотор 177 л.с.", "Спортивный режим"] },
      { title: "Мультимедиа", items: ["Цифровая приборка", "CarPlay"] },
    ],
  },
  {
    id: "atlas",
    brand: "GEELY",
    model: "Atlas",
    year: 2025,
    body: "Кроссовер",
    engine: "2.0 л",
    hp: 200,
    fuel: "Бензин",
    transmission: "Автомат",
    drive: "Полный",
    mileage: 0,
    color: "Белый",
    owners: 0,
    type: "new",
    price: 3199000,
    credit: 27990,
    img: "assets/cars/car-profile.webp",
    gallery: ["assets/cars/car-profile.webp", "assets/cars/car-right2.png"],
    logo: "assets/partners/geely.webp",
    badges: ["Семейный", "Полный привод"],
    equipment: [
      { title: "Комфорт", items: ["Панорама", "3 ряда сидений", "Климат 3 зоны"] },
    ],
  },
  {
    id: "t4",
    brand: "TENET",
    model: "T4",
    year: 2025,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 147,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Полный",
    mileage: 0,
    color: "Серый",
    owners: 0,
    type: "new",
    price: 2249000,
    credit: 19490,
    img: "assets/cars/car1.png",
    gallery: ["assets/cars/car1.png", "assets/hero/hero-1.png"],
    logo: "assets/partners/tenet.webp",
    badges: ["Подарки при покупке"],
    equipment: [
      { title: "Комплектация", items: ["Полный привод", "Камера 360°", "Подогревы"] },
    ],
  },
  {
    id: "t7",
    brand: "TENET",
    model: "T7",
    year: 2025,
    body: "Кроссовер",
    engine: "1.6 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Автомат",
    drive: "Полный",
    mileage: 0,
    color: "Чёрный",
    owners: 0,
    type: "new",
    price: 2699000,
    credit: 23490,
    img: "assets/cars/car-profile.webp",
    gallery: ["assets/cars/car-profile.webp", "assets/hero/hero-2.png"],
    logo: "assets/partners/tenet.webp",
    badges: ["Лидер продаж"],
    equipment: [
      { title: "Премиум", items: ["Кожаный салон", "Панорама", "Адаптивный круиз"] },
    ],
  },
  {
    id: "t8",
    brand: "TENET",
    model: "T8",
    year: 2025,
    body: "Внедорожник",
    engine: "2.0 л",
    hp: 238,
    fuel: "Бензин",
    transmission: "Автомат",
    drive: "Полный",
    mileage: 0,
    color: "Серый",
    owners: 0,
    type: "new",
    price: 3499000,
    credit: 30990,
    img: "assets/cars/car-right2.png",
    gallery: ["assets/cars/car-right2.png", "assets/cars/car-left.webp"],
    logo: "assets/partners/tenet.webp",
    badges: ["Флагман"],
    equipment: [
      { title: "Внедорожье", items: ["Раздатка", "Блокировки", "Режимы Terrain"] },
    ],
  },
  {
    id: "x50",
    brand: "BELGEE",
    model: "X50+",
    year: 2025,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Передний",
    mileage: 0,
    color: "Красный",
    owners: 0,
    type: "new",
    price: 1899000,
    credit: 16490,
    img: "assets/cars/car-right2.png",
    gallery: ["assets/cars/car-right2.png", "assets/cars/car1.png"],
    logo: "assets/partners/belgee.webp",
    badges: ["Спеццена"],
    equipment: [
      { title: "База", items: ["Климат", "Камера", "Круиз"] },
    ],
  },
  {
    id: "x70",
    brand: "BELGEE",
    model: "X70",
    year: 2025,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 147,
    fuel: "Бензин",
    transmission: "Автомат",
    drive: "Передний",
    mileage: 0,
    color: "Белый",
    owners: 0,
    type: "new",
    price: 2199000,
    credit: 19290,
    img: "assets/cars/car-left.webp",
    gallery: ["assets/cars/car-left.webp", "assets/cars/car-right.webp"],
    logo: "assets/partners/belgee.webp",
    badges: ["Семейный"],
    equipment: [
      { title: "Комфорт", items: ["Большой багажник", "Подогрев заднего ряда"] },
    ],
  },
  {
    id: "nc001",
    brand: "NORDCROSS",
    model: "001",
    year: 2025,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 147,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Передний",
    mileage: 0,
    color: "Синий",
    owners: 0,
    type: "new",
    price: 2099000,
    credit: 18290,
    img: "assets/cars/car-left.webp",
    gallery: ["assets/cars/car-left.webp", "assets/hero/hero-1.png"],
    logo: "assets/partners/nordcross.webp",
    badges: ["Новинка"],
    equipment: [
      { title: "Опции", items: ["LED оптика", "Мультируль", "Климат"] },
    ],
  },
  {
    id: "volga-c40",
    brand: "VOLGA",
    model: "C40",
    year: 2025,
    body: "Седан",
    engine: "1.5 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Автомат",
    drive: "Передний",
    mileage: 0,
    color: "Чёрный",
    owners: 0,
    type: "new",
    price: 2499000,
    credit: 21990,
    img: "assets/cars/car-profile.webp",
    gallery: ["assets/cars/car-profile.webp", "assets/cars/car1.png"],
    logo: "assets/partners/volga.webp",
    badges: ["Возвращение легенды"],
    equipment: [
      { title: "Классика", items: ["Просторный салон", "Мягкая подвеска"] },
    ],
  },
  {
    id: "used-jolion",
    brand: "HAVAL",
    model: "Jolion",
    year: 2023,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Передний",
    mileage: 28400,
    color: "Белый",
    owners: 1,
    type: "used",
    price: 1699000,
    credit: 14990,
    img: "assets/cars/car1.png",
    gallery: ["assets/cars/car1.png", "assets/cars/car-right.webp"],
    logo: "assets/partners/used.webp",
    badges: ["1 владелец", "История проверена"],
    equipment: [
      { title: "Состояние", items: ["Сервисная история", "Без ДТП", "Оригинал ПТС"] },
    ],
  },
  {
    id: "used-coolray",
    brand: "GEELY",
    model: "Coolray",
    year: 2022,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Передний",
    mileage: 45200,
    color: "Серый",
    owners: 1,
    type: "used",
    price: 1549000,
    credit: 13690,
    img: "assets/cars/car-right.webp",
    gallery: ["assets/cars/car-right.webp", "assets/cars/car-left.webp"],
    logo: "assets/partners/used.webp",
    badges: ["Trade-in возможен"],
    equipment: [
      { title: "Состояние", items: ["Диагностика на подъёмнике", "Чистый кузов"] },
    ],
  },
  {
    id: "used-t4",
    brand: "TENET",
    model: "T4",
    year: 2024,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 147,
    fuel: "Бензин",
    transmission: "Робот",
    drive: "Полный",
    mileage: 18600,
    color: "Чёрный",
    owners: 1,
    type: "used",
    price: 1899000,
    credit: 16790,
    img: "assets/cars/car-profile.webp",
    gallery: ["assets/cars/car-profile.webp", "assets/cars/car-right2.png"],
    logo: "assets/partners/used.webp",
    badges: ["Полный привод", "Малый пробег"],
    equipment: [
      { title: "Состояние", items: ["Гарантия салона 1 год", "Полный комплект ключей"] },
    ],
  },
  {
    id: "used-x50",
    brand: "BELGEE",
    model: "X50+",
    year: 2023,
    body: "Кроссовер",
    engine: "1.5 л",
    hp: 150,
    fuel: "Бензин",
    transmission: "Механика",
    drive: "Передний",
    mileage: 61000,
    color: "Красный",
    owners: 2,
    type: "used",
    price: 1299000,
    credit: 11490,
    img: "assets/cars/car-right2.png",
    gallery: ["assets/cars/car-right2.png", "assets/cars/car1.png"],
    logo: "assets/partners/used.webp",
    badges: ["Выгодная цена"],
    equipment: [
      { title: "Состояние", items: ["Юридическая чистота", "Готов к выдаче"] },
    ],
  },
];
